// JavaScript source code
// Title:		Authentication
// Created by:	David Kleinot
// Date:		3/31/2020
// Purpose:		This will break out the Authentication portion of the code.

/*
https://authserver.bluebeam.com/auth/oauth/authorize

response_type   Must be set to token
client_id       Client ID received during App registration process; found on Back of App Card.
redirect_uri	Redirect URI specified during App registration process; listed on Front of App Card.
scope	        Space separated list of scopes specified during App registration process; listed on Front of App Card.
state           Random string generated by your App. Studio will return this state in a callback to your redirect_uri.
                Validate it against the state in your App to prevent cross-site request forgery.

*/

//  Constants

//importScripts('./Dashboard.js');
//import { log } from './Dashboard';
//let log = log();


//const Dashboard = require('./Dashboard');

const ClientID = "0dc1f1ba-32a5-4a18-aee2-baafe1cc2ea1";
const Secret = "9c0ae51c-1926-4759-8bf2-f8514691431b";
const response_type = "token";
const redirect_uri = "https://thirsty-kepler-b52ade.netlify.com/Holla_Back.html";
const scope = "full_prime full_user jobs read_prime";

//  Variables

//This will make it easier to turn off debugging
var bDebug = true;
function log(Val) {
    //Simple function to help log stuff to the console.
    if (bDebug) { console.log(Val); }
}

var state = "";

function GenerateState() {
    //This will generate a state and return a random string
    //Math.floor(Math.random() * (36 - 2 + 1) + 2);//generates a random number between 2 and 36.

    //Clear it.
    state = "";

    //create three separate strings with a random base between 2 and 36.
    state = Math.random().toString(Math.floor(Math.random() * (36 - 2 + 1) + 2)).slice(2);
    state += "-" + Math.random().toString(Math.floor(Math.random() * (36 - 2 + 1) + 2)).slice(2);
    state += "-" + Math.random().toString(Math.floor(Math.random() * (36 - 2 + 1) + 2)).slice(2);


    sessionStorage.setItem("state", state);
    //log(state);
}

function Athuenticate() {
    log("This will Authenticate the user?");

    var args = "";

    args = "https://authserver.bluebeam.com/auth/oauth/authorize?response_type=";
    args += response_type;
    args += "&client_id=";
    args += ClientID;
    args += "&redirect_uri=";
    args += redirect_uri;
    args += "&scope=";
    args += scope;

    GenerateState();

    args += "&state=";
    args += state;



    //var Request = new XMLHttpRequest();

    log(args);
    log("returning a website????????????????????");


    //return ("GET " + args);

    window.location.href = args;

    //window.location.href ="GET" + args;

    log("Link done...");

    //Request.open('GET', API_GET_Session + '843-381-486' + '?' + API_KEY , true)
    /*
    Request.open('GET', args, true);
    
    Request.onload = function () {
        // Begin accessing JSON data here
        //var data = JSON.parse(this.response);

        log(this.response);


        if (Request.status = 200) {
            log(data);
        } else {
            console.log('error');
        }
    }

    Request.send();
    */


}